Option Strict On
Option Explicit On

'independent artwork catalog
Friend NotInheritable Class FigureGallery
    Private Shared ReadOnly catalog As Dictionary(Of String, List(Of String)) = LoadCatalog()
    Friend Shared ReadOnly Games As String() = {"Spyro's Adventure", "Giants", "Swap Force", "Trap Team", "SuperChargers", "Imaginators"}

    'keeps this shared helper from being instantiated.
    Private Sub New()
    End Sub

    'builds the game to name catalog for the artwork browsing that some of the pages have
    Private Shared Function LoadCatalog() As Dictionary(Of String, List(Of String))
        Dim result As New Dictionary(Of String, List(Of String))(StringComparer.OrdinalIgnoreCase)
        result.Add("Spyro's Adventure", New List(Of String) From {
            "Bash",
            "Boomer",
            "Camo",
            "Chop Chop",
            "Cynder",
            "Dark Spyro",
            "Dino-Rang",
            "Double Trouble",
            "Drill Sergeant",
            "Drobot",
            "Eruptor",
            "Flameslinger",
            "Ghost Roaster",
            "Gill Grunt",
            "Hex",
            "Ignitor",
            "Legendary Bash",
            "Legendary Chop Chop",
            "Legendary Spyro",
            "Legendary Trigger Happy",
            "Lightning Rod",
            "Prism Break",
            "Slam Bam",
            "Sonic Boom",
            "Spyro",
            "Stealth Elf",
            "Stump Smash",
            "Sunburn",
            "Terrafin",
            "Trigger Happy",
            "Voodood",
            "Warnado",
            "Wham-Shell",
            "Whirlwind",
            "Wrecking Ball",
            "Zap",
            "Zook",
            "Blue Bash",
            "Chrome Spyro",
            "Crystal Clear Cynder",
            "Crystal Clear Stealth Elf",
            "Crystal Clear Wham-Shell",
            "Crystal Clear Whirlwind",
            "Flocked Stump Smash",
            "Glow-in-the-Dark Warnado",
            "Glow-in-the-Dark Wrecking Ball",
            "Glow-in-the-Dark Zap",
            "Gold Chop Chop",
            "Gold Drill Sergeant",
            "Gold Flameslinger",
            "Green Gill Grunt",
            "Metallic Purple Cynder",
            "Pearl Hex",
            "Red Camo",
            "Red Drill Sergeant",
            "Silver Boomer",
            "Silver Dino-Rang",
            "Silver Eruptor"
        })
        result.Add("Giants", New List(Of String) From {
            "Bouncer",
            "Chill",
            "Crusher",
            "Eye-Brawl",
            "Flashwing",
            "Fright Rider",
            "Gnarly Tree Rex",
            "Granite Crusher",
            "Hot Dog",
            "Hot Head",
            "Jade Flashwing",
            "Jet-Vac",
            "Legendary Bouncer",
            "Legendary Chill",
            "Legendary Ignitor",
            "Legendary Jet-Vac",
            "Legendary Slam Bam",
            "Legendary Stealth Elf",
            "LightCore Chill",
            "LightCore Drobot",
            "LightCore Eruptor",
            "LightCore Hex",
            "LightCore Jet-Vac",
            "LightCore Pop Fizz",
            "LightCore Prism Break",
            "LightCore Shroomboom",
            "Molten Hot Dog",
            "Ninjini",
            "Polar Whirlwind",
            "Pop Fizz",
            "Punch Pop Fizz",
            "Royal Double Trouble",
            "Scarlet Ninjini",
            "Series 2 Bash",
            "Series 2 Chop Chop",
            "Series 2 Cynder",
            "Series 2 Double Trouble",
            "Series 2 Drill Sergeant",
            "Series 2 Drobot",
            "Series 2 Eruptor",
            "Series 2 Flameslinger",
            "Series 2 Gill Grunt",
            "Series 2 Hex",
            "Series 2 Ignitor",
            "Series 2 Lightning Rod",
            "Series 2 Prism Break",
            "Series 2 Slam Bam",
            "Series 2 Sonic Boom",
            "Series 2 Spyro",
            "Series 2 Stealth Elf",
            "Series 2 Stump Smash",
            "Series 2 Terrafin",
            "Series 2 Trigger Happy",
            "Series 2 Whirlwind",
            "Series 2 Wrecking Ball",
            "Series 2 Zap",
            "Series 2 Zook",
            "Shroomboom",
            "Sprocket",
            "Swarm",
            "Thumpback",
            "Tree Rex",
            "Stone Whirlwind",
            "Bronze Hot Dog",
            "Double Trouble 1.5",
            "Employee Edition LightCore Prism Break",
            "Glow-in-the-Dark Cynder",
            "Glow-in-the-Dark Fright Rider",
            "Glow-in-the-Dark Sonic Boom",
            "Golden Flameslinger",
            "Halloween Fright Rider",
            "Metallic Blue Chop Chop",
            "Metallic Gill Grunt",
            "Metallic Green Shroomboom",
            "Metallic Purple Eye-Brawl",
            "Metallic Purple Lightning Rod",
            "Metallic Purple Wrecking Ball",
            "Pearl Sprocket",
            "Pumpkin Eye-Brawl",
            "Sparkle Hot Head",
            "Sparkle Sonic Boom",
            "Stone Zook",
            "White Flocked Eruptor",
            "White Flocked LightCore Prism Break",
            "White Flocked Stump Smash",
            "Debug Minion"
        })
        result.Add("Swap Force", New List(Of String) From {
            "Anchors Away Gill Grunt",
            "Boom Jet (Bottom)",
            "Boom Jet (Top)",
            "Big Bang Trigger Happy",
            "Blast Zone (Bottom)",
            "Blast Zone (Top)",
            "Blizzard Chill",
            "Bumble Blast",
            "Countdown",
            "Dark Blast Zone (Bottom)",
            "Dark Blast Zone (Top)",
            "Dark Mega Ram Spyro",
            "Dark Slobber Tooth",
            "Dark Stealth Elf",
            "Dark Wash Buckler (Bottom)",
            "Dark Wash Buckler (Top)",
            "Doom Stone (Bottom)",
            "Doom Stone (Top)",
            "Dune Bug",
            "Enchanted Hoot Loop (Bottom)",
            "Enchanted Hoot Loop (Top)",
            "Enchanted Star Strike",
            "Fire Bone Hot Dog",
            "Fire Kraken (Bottom)",
            "Fire Kraken (Top)",
            "Free Ranger (Bottom)",
            "Free Ranger (Top)",
            "Freeze Blade (Bottom)",
            "Freeze Blade (Top)",
            "Fryno",
            "Grilla Drilla (Bottom)",
            "Grilla Drilla (Top)",
            "Grim Creeper",
            "Heavy Duty Sprocket",
            "Hoot Loop (Bottom)",
            "Hoot Loop (Top)",
            "Horn Blast Whirlwind",
            "Hyper Beam Prism Break",
            "Jade Fire Kraken (Bottom)",
            "Jade Fire Kraken (Top)",
            "Jolly Bumble Blast",
            "Kickoff Countdown",
            "Knockout Terrafin",
            "Lava Barf Eruptor",
            "Legendary Free Ranger (Bottom)",
            "Legendary Free Ranger (Top)",
            "Legendary Grim Creeper",
            "Legendary Night Shift (Bottom)",
            "Legendary Night Shift (Top)",
            "Legendary Zoo Lou",
            "LightCore Bumble Blast",
            "LightCore Countdown",
            "LightCore Flashwing",
            "LightCore Grim Creeper",
            "LightCore Smolderdash",
            "LightCore Star Strike",
            "LightCore Warnado",
            "LightCore Wham-Shell",
            "Magna Charge (Bottom)",
            "Magna Charge (Top)",
            "Mega Ram Spyro",
            "Night Shift (Bottom)",
            "Night Shift (Top)",
            "Ninja Stealth Elf",
            "Nitro Freeze Blade (Bottom)",
            "Nitro Freeze Blade (Top)",
            "Nitro Magna Charge (Bottom)",
            "Nitro Magna Charge (Top)",
            "Phantom Cynder",
            "Pop Thorn",
            "Punk Shock",
            "Quickdraw Rattle Shake (Bottom)",
            "Quickdraw Rattle Shake (Top)",
            "Rattle Shake (Bottom)",
            "Rattle Shake (Top)",
            "Rip Tide",
            "Roller Brawl",
            "Rubble Rouser (Bottom)",
            "Rubble Rouser (Top)",
            "Scorp",
            "Scratch",
            "Slobber Tooth",
            "Smolderdash",
            "Springtime Trigger Happy",
            "Spy Rise (Bottom)",
            "Spy Rise (Top)",
            "Star Strike",
            "Stink Bomb (Bottom)",
            "Stink Bomb (Top)",
            "Super Gulp Pop Fizz",
            "Thorn Horn Camo",
            "Trap Shadow (Bottom)",
            "Trap Shadow (Top)",
            "Turbo Jet-Vac",
            "Twin Blade Chop Chop",
            "Volcanic Eruptor",
            "Wash Buckler (Bottom)",
            "Wash Buckler (Top)",
            "Wind-Up",
            "VVind-Up",
            "Zoo Lou",
            "Red Flame Frito-Lay Fire Bone Hot Dog",
            "Employee Edition LightCore Smolderdash",
            "Flocked Springtime Trigger Happy",
            "Green Chop Chop",
            "Green Flame Frito-Lay Fire Bone Hot Dog",
            "Green Rip Tide",
            "Green Scorp",
            "Heavy Metal Sprocket",
            "Metallic Red Dune Bug",
            "Purple Flame Frito-Lay Fire Bone Hot Dog",
            "Gold & Bronze Doom Stone Bottom",
            "Gold & Bronze Doom Stone Top",
            "Gold Fire Kraken Bottom",
            "Gold Fire Kraken Top",
            "Gold Wash Buckler Bottom",
            "Gold Wash Buckler Top",
            "Silver & Gold Stink Bomb Bottom",
            "Silver & Gold Stink Bomb Top",
            "Bronze & Silver Trap Shadow Bottom",
            "Bronze & Silver Trap Shadow Top",
            "Template Legacy",
            "Template Template Top",
            "Template Template Bottom"
        })
        result.Add("Trap Team", New List(Of String) From {
            "Barkley",
            "Bat Spin",
            "Blackout",
            "Blades",
            "Blastermind",
            "Bop",
            "Breeze",
            "Bushwhack",
            "Chopper",
            "Clear Thunderbolt",
            "Cobra Cadabra",
            "Dark Food Fight",
            "Dark Snap Shot",
            "Dark Wildfire",
            "Drobit",
            "Déjà Vu",
            "Echo",
            "Eggsellent Weeruptor",
            "Elite Chop Chop",
            "Elite Eruptor",
            "Elite Gill Grunt",
            "Elite Spyro",
            "Elite Stealth Elf",
            "Elite Terrafin",
            "Elite Trigger Happy",
            "Elite Whirlwind",
            "Enigma",
            "Eye-Small",
            "Fist Bump",
            "Fizzy Frenzy Pop Fizz",
            "Fling Kong",
            "Flip Wreck",
            "Food Fight",
            "Full Blast Jet-Vac",
            "Funny Bone",
            "Gearshift",
            "Gill Runt",
            "Gnarly Barkley",
            "Gusto",
            "Head Rush",
            "High Five",
            "Hijinx",
            "Hog Wild Fryno",
            "Instant Food Fight",
            "Instant Snap Shot",
            "Jawbreaker",
            "Ka-Boom",
            "King Cobra Cadabra",
            "Knight Light",
            "Knight Mare",
            "Krypt King",
            "Legendary Blades",
            "Legendary Bushwhack",
            "Legendary Déjà Vu",
            "Legendary Jawbreaker",
            "Lob-Star",
            "Love Potion Pop Fizz",
            "Mini-Jini",
            "Nitro Head Rush",
            "Nitro Krypt King",
            "Pet-Vac",
            "Power Punch Pet-Vac",
            "Rocky Roll",
            "Short Cut",
            "Small Fry",
            "Snap Shot",
            "Spotlight",
            "Spry",
            "Sure Shot Shroomboom",
            "Terrabite",
            "Thumpling",
            "Thunderbolt",
            "Tidal Wave Gill Grunt",
            "Torch",
            "Trail Blazer",
            "Tread Head",
            "Trigger Snappy",
            "Tuff Luck",
            "Wallop",
            "Weeruptor",
            "Whisper Elf",
            "Wildfire",
            "Winterfest Lob-Star",
            "Clear Short Cut",
            "Clear Tuff Luck"
        })
        result.Add("SuperChargers", New List(Of String) From {
            "Astroblast",
            "Big Bubble Pop Fizz",
            "Birthday Bash Big Bubble Pop Fizz",
            "Bone Bash Roller Brawl",
            "Bronze Bone Bash Roller Brawl",
            "Dark Hammer Slam Bowser",
            "Dark Spitfire",
            "Dark Super Shot Stealth Elf",
            "Dark Turbo Charge Donkey Kong",
            "Deep Dive Gill Grunt",
            "Dive-Clops",
            "Double Dare Trigger Happy",
            "Eggcited Thrillipede",
            "Elite Boomer",
            "Elite Dino-Rang",
            "Elite Ghost Roaster",
            "Elite Slam Bam",
            "Elite Voodood",
            "Elite Zook",
            "Fiesta",
            "Frightful Fiesta",
            "Hammer Slam Bowser",
            "High Volt",
            "Hurricane Jet-Vac",
            "Instant Dive-Clops",
            "Instant Spitfire",
            "Instant Super Shot Stealth Elf",
            "Lava Lance Eruptor",
            "Patina High Volt",
            "Patina Lava Lance Eruptor",
            "Legendary Astroblast",
            "Legendary Bone Bash Roller Brawl",
            "Legendary Hurricane Jet-Vac",
            "Legendary Sun Runner",
            "Missile-Tow Dive-Clops",
            "Nightfall",
            "Power Blue Splat",
            "Power Blue Trigger Happy",
            "Shark Shooter Terrafin",
            "Smash Hit",
            "Spitfire",
            "Splat",
            "Steel Plated Smash Hit",
            "Snow-Brite Stormblade (Employee Edition)",
            "Stormblade",
            "Super Shot Stealth Elf",
            "Thrillipede",
            "Turbo Charge Donkey Kong",
            "Kaos Trophy",
            "Land Trophy",
            "Sea Trophy",
            "Sky Trophy"
        })
        result.Add("Imaginators", New List(Of String) From {
            "Air Strike",
            "Ambush",
            "Aurora",
            "Bad Juju",
            "Barbella",
            "Blaster-Tron",
            "Boom Bloom",
            "Buckshot",
            "Candy-Coated Chopscotch",
            "Chain Reaction",
            "Chompy Mage",
            "Chopscotch",
            "Clear Starcast",
            "Crash Bandicoot",
            "Dark Golden Queen",
            "Dark King Pen",
            "Dark Wolfgang",
            "Dec-Ember (Employee Edition)",
            "Dr. Krankcase",
            "Dr. Neo Cortex",
            "Egg Bomber Air Strike",
            "Ember",
            "Flarewolf",
            "Golden Queen",
            "Grave Clobber",
            "Hard-Boiled Flarewolf",
            "Happy Birthday Ben Starcast",
            "Heartbreaker Buckshot",
            "Hood Sickle",
            "Jingle Bell Chompy Mage",
            "Kaos",
            "King Pen",
            "Legendary Pit Boss",
            "Legendary Tri-Tip",
            "Mystical Bad Juju",
            "Mystical Tae Kwon Crow",
            "Mysticat",
            "Orange Chain Reaction",
            "Pain-Yatta",
            "Pink Barbella",
            "Pit Boss",
            "Ro-Bow",
            "Rock Candy Pain-Yatta",
            "Solar Flare Aurora",
            "Starcast",
            "Steel Plated Hood Sickle",
            "Tae Kwon Crow",
            "Tidepool",
            "Tri-Tip",
            "Wild Storm",
            "Wolfgang"
        })
        result.Add("Vehicles", New List(Of String) From {
            "Barrel Blaster",
            "Bronze Tomb Buggy",
            "Burn-Cycle",
            "Crypt Crusher",
            "Dark Barrel Blaster",
            "Dark Hot Streak",
            "E3 Hot Streak",
            "Gold Rusher",
            "Golden Hot Streak",
            "Hot Streak",
            "Instant Hot Streak",
            "Power Blue Gold Rusher",
            "Patina Burn-Cycle",
            "Patina Shield Striker",
            "Shark Tank",
            "Shield Striker",
            "Thump Truck",
            "Tomb Buggy",
            "Dark Sea Shadow",
            "Dive Bomber",
            "Instant Dive Bomber",
            "Nitro Soda Skimmer",
            "Power Blue Splatter Splasher",
            "Reef Ripper",
            "Sea Shadow",
            "Soda Skimmer",
            "Splatter Splasher",
            "Spring Ahead Dive Bomber",
            "Buzz Wing",
            "Clown Cruiser",
            "Dark Clown Cruiser",
            "Jet Stream",
            "Nitro Stealth Stinger",
            "Sky Slicer",
            "Stealth Stinger",
            "Instant Stealth Stinger",
            "Sun Runner"
        })
        Return result
    End Function

    'Yes, i know there are a ton more, but I did not feel like adding art for abolsutely everything as of this point

    'returns browsing names from the category requested
    Friend Shared Function Names(game As String) As List(Of String)
        Dim namesVar As List(Of String) = Nothing
        If catalog.TryGetValue(game, namesVar) Then Return New List(Of String)(namesVar)
        Return New List(Of String)()
    End Function
End Class

'Presents independent collapsible game sections; selection is artwork only and never changes tag data.
Friend Class SkyGameBrowser
    Inherits UserControl
    Private ReadOnly stack As New TableLayoutPanel With {.Dock = DockStyle.Top, .AutoSize = True, .ColumnCount = 1, .Margin = New Padding(0)}
    Friend Property SelectedGame As String
    Friend Property SelectedFigure As String
    Friend Event PreviewChanged As EventHandler

    Friend Sub New()
        DoubleBuffered = True
        AutoScroll = True
        BackColor = SkyAssets.Panel
        stack.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
        Controls.Add(stack)
    End Sub

    'Populates all sections in the collapsed state, with a separately scrollable list under each heading.
    Friend Sub LoadCatalog()
        SuspendLayout()
        For Each game As String In FigureGallery.Games.Concat(New String() {"Vehicles"})
            Dim title As String = game
            Dim section As New TableLayoutPanel With {.Dock = DockStyle.Top, .AutoSize = True, .ColumnCount = 1, .Margin = New Padding(2, 1, 2, 1)}
            section.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100))
            Dim header As New Button With {.Text = title & "  +", .Dock = DockStyle.Top, .Height = CInt(32 * DeviceDpi / 96.0F), .Font = SkyAssets.UiFont(7.0F),
                .FlatStyle = FlatStyle.Flat, .BackColor = GameColor(title), .ForeColor = If(title = "Imaginators", Color.White, Color.Black), .UseVisualStyleBackColor = False}
            header.FlatAppearance.BorderSize = 0
            Dim entries As New ListBox With {.Dock = DockStyle.Top, .Height = CInt(180 * DeviceDpi / 96.0F), .Font = SkyAssets.UiFont(7.0F),
                .BackColor = SkyAssets.White, .ForeColor = Color.Black, .BorderStyle = BorderStyle.None, .IntegralHeight = False, .Visible = False, .HorizontalScrollbar = True}
            entries.Items.AddRange(FigureGallery.Names(title).Cast(Of Object)().ToArray())
            AddHandler header.Resize, Sub(sender, e) SkyPolish.RoundControl(header, 10)
            AddHandler header.Click, Sub(sender, e)
                                         entries.Visible = Not entries.Visible
                                         header.Text = title & If(entries.Visible, "  −", "  +")
                                     End Sub
            AddHandler entries.MouseMove, Sub(sender, e)
                                              Dim index As Integer = entries.IndexFromPoint(e.Location)
                                              If index >= 0 AndAlso index <> entries.SelectedIndex Then entries.SelectedIndex = index
                                          End Sub
            AddHandler entries.SelectedIndexChanged, Sub(sender, e)
                                                         If entries.SelectedIndex < 0 Then Return
                                                         SelectedGame = title
                                                         SelectedFigure = CStr(entries.SelectedItem)
                                                         RaiseEvent PreviewChanged(Me, EventArgs.Empty)
                                                     End Sub
            section.Controls.Add(header, 0, 0)
            section.Controls.Add(entries, 0, 1)
            stack.Controls.Add(section, 0, stack.RowCount)
            stack.RowCount += 1
        Next
        ResumeLayout(True)
    End Sub

    'COLOR PICKER FOR THE DROPDOWNS
    Private Shared Function GameColor(game As String) As Color
        Select Case game
            Case "Spyro's Adventure" : Return Color.FromArgb(0, 255, 26)
            Case "Giants" : Return Color.FromArgb(253, 155, 20)
            Case "Swap Force" : Return Color.FromArgb(82, 207, 224)
            Case "Trap Team" : Return Color.FromArgb(254, 60, 57)
            Case "SuperChargers" : Return Color.FromArgb(249, 240, 0)
            Case "Imaginators" : Return Color.FromArgb(18, 33, 123)
            Case Else : Return Color.FromArgb(188, 96, 222)
        End Select
    End Function
End Class
